### PR TITLE
readme: declare PODS_ALT_CACHE_MEMCACHED_PORT int

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by Ramoonus** [comment]
classes/Pods/Alternative/Cache/Memcached.php:160

**Comment by sc0ttkclark** [comment]
Should we cast as int in usage too? In case people define as strings? Or does that not matter?

**Comment by Ramoonus** [comment]
i think yes
validation, since a text string will surely break things

**Comment by Ramoonus** [comment]
it`s not backwards compatible yet
need to do one more patch

**Pull request merged**
